---
- name: Install Nagios packages
  ansible.builtin.yum:
    name:
      - nagios
      - nagios-plugins-all
      - nagios-plugins-nrpe
    state: present

- name: Enable and start Nagios service
  ansible.builtin.service:
    name: nagios
    enabled: true
    state: started
