---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
- name: Set timezone
  ansible.builtin.command: timedatectl set-timezone America/Chicago
  changed_when: false

- name: Install EPEL on RHEL 7/8
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_distribution == "RedHat" and (ansible_distribution_major_version | int) < 9
