---
- name: Ensure admin group exists
  ansible.builtin.group:
    name: admins
    state: present

- name: Create admin user
  ansible.builtin.user:
    name: oluadmin
    comment: "Olumide Admin"
    shell: /bin/bash
    groups: admins
    append: true
    state: present

- name: Set authorized key for oluadmin
  ansible.posix.authorized_key:
    user: oluadmin
    state: present
    key: "{{ lookup('file', 'files/oluadmin_id_rsa.pub') }}"
