---
- name: Publish local repos with exact Apache aliases (reposync.corp.local)
  hosts: reposync.corp.local
  become: true
  gather_facts: false

  vars:
    # Add/remove roots if you stash mirrors elsewhere
    search_roots:
      - /var/www/html
      - /var/www
      - /mnt/hp2-repo
      - /var/repos
      - /var/lib/repos

  tasks:
    - name: Find BaseOS directory that contains repodata/repomd.xml
      shell: |
        bash -lc '
        shopt -s nullglob globstar
        for root in {{ search_roots | join(" ") }}; do
          for p in \
            "$root/centos-stream/9/baseos" \
            "$root/repos/el9/BaseOS/x86_64/os" \
            "$root"/**/baseos
          do
            if [ -f "$p/repodata/repomd.xml" ]; then
              readlink -f "$p"; exit 0
            fi
          done
        done
        exit 1
        '
      register: baseos_dir
      changed_when: false

    - name: Find AppStream directory that contains repodata/repomd.xml
      shell: |
        bash -lc '
        shopt -s nullglob globstar
        for root in {{ search_roots | join(" ") }}; do
          for p in \
            "$root/centos-stream/9/appstream" \
            "$root/repos/el9/AppStream/x86_64/os" \
            "$root"/**/appstream
          do
            if [ -f "$p/repodata/repomd.xml" ]; then
              readlink -f "$p"; exit 0
            fi
          done
        done
        exit 1
        '
      register: appstream_dir
      changed_when: false

    - name: Find CRB directory that contains repodata/repomd.xml
      shell: |
        bash -lc '
        shopt -s nullglob globstar
        for root in {{ search_roots | join(" ") }}; do
          for p in \
            "$root/centos-stream/9/crb" \
            "$root/repos/el9/CRB/x86_64/os" \
            "$root"/**/crb
          do
            if [ -f "$p/repodata/repomd.xml" ]; then
              readlink -f "$p"; exit 0
            fi
          done
        done
        exit 1
        '
      register: crb_dir
      changed_when: false

    - name: Assert all channels were located
      assert:
        that:
          - baseos_dir.rc == 0
          - appstream_dir.rc == 0
          - crb_dir.rc == 0
        fail_msg: "Could not locate one or more channels. Check mirror paths and re-run."

    - name: Write Apache aliases (canonical + legacy) to exact dirs
      copy:
        dest: /etc/httpd/conf.d/repo-compat-alias.conf
        mode: '0644'
        content: |
          # Autogenerated exact aliases
          Alias /centos-stream/9/baseos {{ baseos_dir.stdout }}
          Alias /centos-stream/9/appstream {{ appstream_dir.stdout }}
          Alias /centos-stream/9/crb {{ crb_dir.stdout }}
          Alias /repos/el9/BaseOS/x86_64/os {{ baseos_dir.stdout }}
          Alias /repos/el9/AppStream/x86_64/os {{ appstream_dir.stdout }}
          Alias /repos/el9/CRB/x86_64/os {{ crb_dir.stdout }}

          <Directory "{{ baseos_dir.stdout | dirname | dirname }}">
            Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted
          </Directory>
          <Directory "{{ appstream_dir.stdout | dirname | dirname }}">
            Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted
          </Directory>
          <Directory "{{ crb_dir.stdout | dirname | dirname }}">
            Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted
          </Directory>
      notify: reload httpd

    - name: Restore SELinux labels on likely trees
      command: restorecon -RF {{ item }}
      loop: "{{ search_roots }}"
      changed_when: false
      failed_when: false

    - name: Verify endpoints (expect 200)
      uri:
        url: "http://127.0.0.1{{ item }}"
        method: HEAD
        status_code: 200
      register: url_checks
      loop:
        - /centos-stream/9/baseos/repodata/repomd.xml
        - /centos-stream/9/appstream/repodata/repomd.xml
        - /centos-stream/9/crb/repodata/repomd.xml
        - /repos/el9/BaseOS/x86_64/os/repodata/repomd.xml
        - /repos/el9/AppStream/x86_64/os/repodata/repomd.xml
        - /repos/el9/CRB/x86_64/os/repodata/repomd.xml

    - name: Assert all 6 URLs return 200 OK
      assert:
        that: "url_checks.results | map(attribute='status') | list | select('equalto', 200) | length == 6"
        fail_msg: "One or more repo URLs did not return 200. Check alias or mirror content."

  handlers:
    - name: reload httpd
      service:
        name: httpd
        state: reloaded

