- name: Canary install with correct base + EPEL selection (robust + override)
  hosts: rhel_servers
  become: true
  gather_facts: true
  any_errors_fatal: true
  strategy: linear
  serial: 2

  vars:
    canary_pkg: htop
    # Heads we can probe (we don't probe RHSM)
    stream_heads:
      - http://reposync.corp.local/centos-stream/9/baseos/repodata/repomd.xml
      - http://reposync.corp.local/centos-stream/9/appstream/repodata/repomd.xml
      - http://reposync.corp.local/centos-stream/9/crb/repodata/repomd.xml
      - http://reposync.corp.local/repos/el9/epel-next/repodata/repomd.xml
    epel9_head: http://reposync.corp.local/repos/el9/epel/repodata/repomd.xml
    # optional per-host override; set in host_vars/<host>.yml if needed:
    # force_epel_variant: next | epel
    # default: unset (auto-detect)

  pre_tasks:
    - name: Decide EL version + RHEL facts
      set_fact:
        is_el9: "{{ (ansible_facts.os_family == 'RedHat') and (ansible_facts.distribution_major_version | int == 9) }}"
        is_rhel: "{{ (ansible_facts.distribution | lower) is search('red hat') }}"
        rhel_arch_crb: "codeready-builder-for-rhel-9-{{ ansible_architecture }}-rpms"

    # --- three independent detectors for "Streamish" ---
    - name: Detector A (repo names mention CentOS Stream)
      shell: dnf -q repolist --enabled | grep -qi 'CentOS Stream' && echo yes || echo no
      register: detect_name
      changed_when: false

    - name: Detector B (any baseurl contains /centos-stream/9/)
      shell: |
        grep -RhoE '^\s*baseurl\s*=\s*\S+' /etc/yum.repos.d/*.repo 2>/dev/null \
        | grep -q '/centos-stream/9/' && echo yes || echo no
      register: detect_url
      changed_when: false

    - name: Detector C (centos-stream-release package)
      shell: rpm -q centos-stream-release >/dev/null 2>&1 && echo yes || echo no
      register: detect_pkg
      changed_when: false

    - name: Consolidate detection and apply override if present
      set_fact:
        is_streamish_detected: "{{ (detect_name.stdout|default('no')=='yes') or
                                  (detect_url.stdout|default('no')=='yes') or
                                  (detect_pkg.stdout|default('no')=='yes') }}"
        override_next: "{{ (force_epel_variant | default('') | lower) in ['next','epel-next','epel_next'] }}"
        override_epel: "{{ (force_epel_variant | default('') | lower) in ['epel','9','epel-9'] }}"
        is_streamish: "{{ override_next | ternary(true, (override_epel | ternary(false, is_streamish_detected))) }}"

    - name: Build repo enable list per host
      set_fact:
        enable_repos: >-
          {{
            is_rhel
            | ternary(
                'epel-local,rhel-9-baseos-rpms,rhel-9-appstream-rpms,' ~ rhel_arch_crb,
                (is_streamish
                  | ternary('epel-next-local,local-baseos,local-appstream,local-crb',
                            'epel-local,local-baseos,local-appstream,local-crb'))
              )
          }}

    - name: Skip non-EL9
      meta: end_host
      when: not is_el9

    - name: HEAD checks (only our mirrors; RHSM not probed)
      uri:
        url: "{{ item }}"
        method: HEAD
        status_code: 200
        timeout: 5
        return_content: no
      loop: "{{ is_streamish | ternary(stream_heads, [epel9_head]) }}"
      changed_when: false

  tasks:
    - name: Makecache from ONLY our selected repos
      dnf:
        name: "*"
        state: latest
        update_cache: yes
        disablerepo: "*"
        enablerepo: "{{ enable_repos }}"
      changed_when: false

    - name: Install canary package
      dnf:
        name: "{{ canary_pkg }}"
        state: present
        disablerepo: "*"
        enablerepo: "{{ enable_repos }}"
        update_cache: yes

    - name: Verify install
      shell: "rpm -qi {{ canary_pkg }} | egrep 'Name|Version|Release|Vendor'"
      register: pkg_info
      changed_when: false

    - debug:
        msg: "{{ inventory_hostname }} => RHEL={{is_rhel}} Streamish={{is_streamish}} Override={{force_epel_variant|default('')}} Repos={{enable_repos}}"
    - debug:
        var: pkg_info.stdout_lines

