---
# Enforce local repos on RedHat-like EL9 hosts
- name: Enforce local repos on RedHat-like EL9 hosts
  hosts: redhat_like
  gather_facts: true
  gather_subset:
    - min           # fast facts; includes distro/version needed by repo_guardrails
    - '!hardware'   # avoid mounts scan that causes CIFS timeouts
  gather_timeout: 30  # seconds
  roles:
    - role: repo_guardrails
      tags: ['repo_guardrails']

# Configure monitoring server
- name: Configure monitoring server
  hosts: monitoring
  gather_facts: true
  gather_subset:
    - min
  gather_timeout: 30
  roles:
    - role: monitoring
      tags: ['monitoring']

# Configure backup automation
- name: Configure backup automation
  hosts: backup
  gather_facts: true
  gather_subset:
    - min
  gather_timeout: 30
  roles:
    - role: backup
      tags: ['backup']

