---
- name: Apply base configuration to all servers
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - common
    - user-management

- name: Apply monitoring configuration
  hosts: monitoring
  become: true
  roles:
    - monitoring

- name: Apply backup configuration
  hosts: backup
  become: true
  roles:
    - backup
