---
- name: Update repos and apply upgrades on Ubuntu
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages (dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

