galaxy_info:
  author: Olumide
  description: Backup role for rsync and logrotate
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: EL
      versions:
        - 7.2
        - 8
        - 9
    - name: Ubuntu
      versions:
        - all

