name: Auto-Clean README Weekly

on:
  schedule:
    - cron: '0 7 * * 0'  # Every Sunday at 7 AM UTC
  workflow_dispatch:     # Allow manual trigger

permissions:
  contents: write

jobs:
  sanitize-readme:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script to Clean README
        shell: pwsh
        run: ./upgrade-readme.ps1
        working-directory: ${{ github.workspace }}

      - name: Commit changes if needed
        shell: bash
        run: |
          set -e
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --cached --exit-code || git commit -m "Auto-clean README"
          git push origin HEAD --force-with-lease

