name: Ansible CI
on: [push, pull_request]
jobs:
  lint-and-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install ansible ansible-lint yamllint
      - run: yamllint .
      - run: ansible-lint
      - name: Syntax-check playbooks
        run: |
          for p in ansible/playbooks/*.yml; do
            echo "::group::Syntax $p"
            ansible-playbook -i 'localhost,' -c local "$p" --syntax-check
            echo "::endgroup::"
          done

