name: Ansible CI (PR-only)

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-syntax:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CONFIG: ansible/ansible.cfg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible + (optional) linter
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core==2.15.*" "ansible-lint==6.*"

      - name: Prepare vault pass
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}
        run: |
          mkdir -p ~/.config/ansible
          printf "%s" "$ANSIBLE_VAULT_PASS" > ~/.config/ansible/.vault-pass
          chmod 600 ~/.config/ansible/.vault-pass

      # Lint is advisory: it can talk, but it cannot block
      - name: Lint (advisory, YAML plugin off, narrowed scope)
        continue-on-error: true
        run: |
          ansible-lint ansible/playbooks \
            -x yaml,name[casing],risky-shell-pipe,fqcn[action],no-changed-when \
            --exclude 'ansible/group_vars/*.vault.yml' \
            --exclude 'ansible/docs' \
            --exclude 'ansible/mycollections' || true

      # This is the only gating step
      - name: Syntax check all playbooks (gating)
        run: |
          set -e
          for p in ansible/playbooks/*.yml; do
            echo "::group::Syntax check $p"
            ansible-playbook -i ansible/inventory --syntax-check "$p"
            echo "::endgroup::"
          done
