name: Ansible CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling (ansible, ansible-lint, yamllint)
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      # Keep yamllint signal, but don't block the pipeline while we stabilize.
      # It’s scoped to Ansible code paths only.
      - name: yamllint (scoped; non-blocking)
        continue-on-error: true
        run: |
          paths="ansible/ playbooks/ roles/"
          if [ -f .yamllint ]; then
            yamllint -c .yamllint $paths || true
          else
            yamllint $paths || true
          fi

      - name: ansible-lint
        run: |
          if [ -f .ansible-lint ]; then
            ansible-lint -v
          else
            ansible-lint -v --nocolor
          fi

      - name: Ansible --syntax-check all playbooks
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=()
          for d in ansible/playbooks playbooks; do
            for f in "$d"/*.yml "$d"/*.yaml; do
              files+=("$f")
            done
          done
          if [ ${#files[@]} -eq 0 ]; then
            echo "No playbooks found under ansible/playbooks or playbooks"
            exit 0
          fi
          for p in "${files[@]}"; do
            echo "::group::Syntax ${p}"
            ansible-playbook -i 'localhost,' -c local "$p" --syntax-check
            echo "::endgroup::"
          done

