name: Ansible CI (PR-only)

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-syntax:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CONFIG: ansible/ansible.cfg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible + linters
        run: |
          python -m pip install "ansible-core==2.15.*" "ansible-lint==6.*" yamllint
          pip install "ansible-core==2.15.*" "ansible-lint==6.*" yamllint

      - name: Prepare vault pass (for syntax-check)
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}
        run: |
          mkdir -p ~/.config/ansible
          printf "%s" "$ANSIBLE_VAULT_PASS" > ~/.config/ansible/.vault-pass
          chmod 600 ~/.config/ansible/.vault-pass

      - name: Lint (ansible-lint)
        run: |
          ansible-lint ansible/ -x yaml --exclude "ansible/group_vars/*.vault.yml" --exclude "ansible/docs"

      - name: Syntax check all playbooks
        run: |
          set -e
          for p in ansible/playbooks/*.yml; do
            echo "::group::Syntax check $p"
            ansible-playbook -i ansible/inventory --syntax-check "$p"
            echo "::endgroup::"
          done

