name: Pages Smoke Test
on:
  workflow_run:
    workflows: ["pages build and deployment"]
    types: [completed]
jobs:
  smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          BASE="https://lummidizzle.github.io/homelab-infrastructure-projects"
          for p in / /monitoring/ ; do
            echo "Checking $BASE$p"
            curl -fsSIL "$BASE$p" >/dev/null
          done

